version: 2.1

jobs:
  validate:
    docker:
    - image: python:3.8
    environment:
      BASE_COMMIT: << pipeline.git.base_revision >>
      REVISION_COMMIT: <<pipeline.git.revision>>
    steps:
    - checkout
    - run:
        name: Validate config files
        command: |
          venv/bin/pip install -r .script/requirements.txt
          changed_files=$(git diff --name-only $BASE_COMMIT..$REVISION_COMMIT -- '*.toml' '*.toml.example')
          echo "Run validation on changed files: "
          echo $changed_files
          venv/bin/python3 .script/validate.py $changed_files
  docs:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "98:ba:de:b1:23:71:8d:0a:c2:98:98:ac:e8:97:ae:0d"
      - run:
          name: Build and deploy docs
          command: |
            python3.8 -m venv venv/
            venv/bin/pip install -r .script/requirements.txt
            venv/bin/python3 .script/generate_docs.py \
              --output_dir=generated_docs/
            cd generated_docs/
            PATH="../venv/bin:$PATH" mkdocs gh-deploy \
              -m "[ci skip] Deployed {sha} with MkDocs version: {version}"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - docs:
          filters:
            branches:
              only: main