friendly_name = "New Tab - Do No Harm"
description = """
Guardrail metrics for the New Tab. Includes user experience and revenue-related metrics for Search, Pocket and AdMarketplace Sponsored Tiles.
"""

[metrics]
weekly = [
    "newtab_searches", 
    "newtab_ad_clicks",
    "newtab_homepage_enabled",
    # TO DO: Add combined engagement metric
]

overall = [
    "newtab_searches", 
    "newtab_ad_clicks",
    "newtab_homepage_enabled",
    # TO DO: Add combined engagement metric
]

[metrics.newtab_searches.statistics.bootstrap_mean]
[metrics.newtab_searches.statistics.deciles]

[metrics.newtab_ad_clicks.statistics.bootstrap_mean]
[metrics.newtab_ad_clicks.statistics.deciles]

[metrics.newtab_homepage_enabled.statistics.binomial]