---
site_name: Metric Hub
site_description: Metric Definitions
site_author: Mozilla Data Platform Team

# Repository
repo_name: mozilla/metric-hub
repo_url: https://github.com/mozilla/metric-hub/
edit_uri: ""

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: teal
  favicon: favicon.png
  custom_dir: overrides

plugins:
  - search
  - awesome-pages
nav:
  - index.md
  - Outcomes:
      - ... | outcomes/**/**.md
  - Metrics:
      - ... | metrics/**.md
  - Data Sources:
      - ... | data_sources/**.md
  - Segments:
      - ... | segments/**.md
  - Segment Data Sources:
      - ... | segment_data_sources/**.md
  - Dimensions:
      - ... | dimensions/**.md    
  - Default Configs:
      - ... | default_configs/**.md
  - Functions:
      - ... | functions.md
